//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITP_SH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectTB
    {
        public int SubjectCode { get; set; }
        public string SubjectName { get; set; }
        public string Grade { get; set; }
        public string Teacher { get; set; }
    
        public virtual GradeList GradeList { get; set; }
        public virtual SubjectDetail SubjectDetail { get; set; }
        public virtual TeacherList TeacherList { get; set; }
    }
}
