//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITP_SH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectDetail
    {
        public int SubjectID { get; set; }
        public string Hall { get; set; }
        public string Day { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    
        public virtual SubjectTB SubjectTB { get; set; }
    }
}
